[package]
name = "journal"
version = "0.1.0"
authors = ["dbxnr <dbxnr@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "2.33"
confy = "0.4"
gag = "0.1.10" # Silence vader_sentiment"
serde = { version = "1.0", features = ["derive"] }
vader_sentiment = "0.1"
