[package]
name = "notebook_rs"
version = "0.2.1"
authors = ["K Malachi Mulligan <kevinmalachimulligan@protonmail.com>"]
edition = "2018"
repository = "https://github.com/dbxnr/notebook_rs"
homepage = "https://github.com/dbxnr/notebook_rs"
description = "CLI utility for plaintext notetaking"
license = "MIT"
keywords = ["notebook", "journal"]
categories = ["command-line-utilities"]
readme = "README.md"
exclude = ["data/*"]

[dependencies]
anyhow = "1.0"
directories = "3.0"
chrono = "0.4"
clap = "2.33"
confy = "0.4"
gag = "0.1"
serde = { version = "1.0", features = ["derive"] }
vader_sentiment = "0.1"

[[bin]]
name = "nb"
path = "src/main.rs"
