[package]
name = "notebook_rs"
version = "0.1.0"
authors = ["K Malachi Mulligan <kevinmalachimulligan@protonmail.com>"]
edition = "2018"
repository = "https://github.com/dbxnr/notebook-rs"

[dependencies]
chrono = "0.4"
clap = "2.33"
confy = "0.4"
serde = { version = "1.0", features = ["derive"] }
vader_sentiment = { git = "https://github.com/dbxnr/vader-sentiment-rust.git" }

[[bin]]
name = "nb"
path = "src/main.rs"
