[package]
name = "notebook_rs"
version = "0.4.0"
authors = ["K Malachi Mulligan <kevinmalachimulligan@protonmail.com>"]
edition = "2021"
repository = "https://github.com/dbxnr/notebook_rs"
homepage = "https://github.com/dbxnr/notebook_rs"
description = "CLI utility for plaintext notetaking"
license = "MIT"
keywords = ["notebook", "journal"]
categories = ["command-line-utilities"]
readme = "README.md"
exclude = ["data/*"]

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
directories = "4.0"
chrono = "0.4"
clap = "3.0"
confy = "0.4"
regex = "1.5"
serde = { version = "1.0", features = ["derive"] }
vader_sentiment = "0.1"

[[bin]]
name = "nb"
path = "src/main.rs"
